Keybinding.bind(
  { leader = true, noremap = true },
  { "xc", "<cmd>ShellTerminateInput<CR>", { name = "shell_terminate_input" } },
  { "xd", "<cmd>ShellDock<CR>", { name = "shell_dock" } },
  { "xx", "<cmd>ShellStart<CR>", { name = "shell_start" } },
  { "xs", "<cmd>ShellSplit<CR>", { name = "shell_split" } },
  { "xv", "<cmd>ShellVsplit<CR>", { name = "shell_vsplit" } },
  { "xk", "<cmd>ShellHide<CR>", { name = "shell_hide" } },
  { "xq", "<cmd>ShellStop<CR>", { name = "shell_stop" } },
  { "xe", "<cmd>ShellSendLine<CR>", { name = "shell_send_line" } },
  { "xb", "<cmd>ShellSendBuffer<CR>", { name = "shell_send_buffer" } },
  { "x.", "<cmd>ShellSendTillPoint<CR>", { name = "shell_send_till_point" } },
  { "rd", "<cmd>REPLDock<CR>", { name = "repl_dock" } },
  { "rr", "<cmd>REPLStart<CR>", { name = "repl_start" } },
  { "rs", "<cmd>REPLSplit<CR>", { name = "repl_split" } },
  { "rv", "<cmd>REPLVsplit<CR>", { name = "repl_vsplit" } },
  { "rk", "<cmd>REPLHide<CR>", { name = "repl_hide" } },
  { "rq", "<cmd>REPLStop<CR>", { name = "repl_stop" } },
  { "rQ", REPL.stopall, { desc = "Stop all REPLs", name = "stop_all" } },
  { "re", "<cmd>REPLSendLine<CR>", { name = "repl_send_line" } },
  { "rb", "<cmd>REPLSendBuffer<CR>", { name = "repl_send_buffer" } },
  { "r.", "<cmd>REPLSendTillPoint<CR>", { name = "repl_send_till_point" } },
  { "re", "<esc>:REPLSendRange<CR>", { name = "repl_send_range", mode = "v" } },
  { "xe", "<esc>:ShellSendRange<CR>", { mode = "v", name = "shell_send_range" } },
  { "rc", "<cmd>TerminateInput<CR>", { name = "repl_terminate_input" } }
)
