#!/bin/bash

HELP='Install required luarocks for doom'
[[ $1 =~ -h ]] && echo $HELP && exit 1

rocks=(penlight lualogging lrexlib-pcre2)
for rock in ${rocks[@]}; do
    luarocks \
        --local \
        --lua-version 5.1\
        install $rock
done

