#!/bin/bash

[[ $EUID -ne 0 ]] && echo 'Need root privileges to install packages' && exit 1

arch=(fd ripgrep)
debian=(fd-find ripgrep libpcre2-dev luarocks lua5.1)
use=${1:-arch}

if [[ $use =~ arch ]]; then
    for pkg in "${arch[@]}" ; do
        sudo pacman -S "$pkg"
    done
else
    for pkg in "${debian[@]}" ; do
        sudo apt-get install "$pkg"
    done
fi
