require("core.globals")
require("core.option")
require("core.autocmd")
require("core.kbd")
require("core.kbd.eval")
-- builtin.require("core.pkg")
-- builtin.require("core.repl")
-- builtin.require("core.repl.keybindings")
-- builtin.require("core.autocmd.defaults")
-- builtin.require("core.repl.defaults")
-- return builtin.require("core.kbd.defaults")
