require 'core.utils'
require 'core.globals'
require 'core.logger'

user.require 'core.utils.autocmd'
user.require 'core.keybindings'
user.require 'core.packages'
user.require 'core.repl'
user.require 'core.keybindings.defaults'
user.require 'core.repl.keybindings'
user.require 'core.repl.autocmds'
user.require 'core.autocmds.defaults'
