require("core.globals")
require("core.option")
require("core.netrw")
require("core.bookmarks")
require("core.defaults")
require("core.lang")
require("core.repl")
require("core.colorscheme")
require("core.plugins")
-- require 'core.bufgroups'
